<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.tkit.onecx</groupId>
        <artifactId>onecx-quarkus3-parent</artifactId>
        <version>${parentVersion}</version>
    </parent>

    <artifactId>${artifactId}</artifactId>
    <name>${projectDisplayName}</name>
    <version>999-SNAPSHOT</version>
${packaging}

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.openapi.generator</groupId>
            <artifactId>quarkus-openapi-generator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>org.tkit.quarkus.lib</groupId>
            <artifactId>tkit-quarkus-log-cdi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.tkit.quarkus.lib</groupId>
            <artifactId>tkit-quarkus-log-rs</artifactId>
        </dependency>
        <dependency>
            <groupId>org.tkit.quarkus.lib</groupId>
            <artifactId>tkit-quarkus-log-json</artifactId>
        </dependency>
        <dependency>
            <groupId>org.tkit.quarkus.lib</groupId>
            <artifactId>tkit-quarkus-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>org.tkit.quarkus.lib</groupId>
            <artifactId>tkit-quarkus-rest-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.tkit.onecx.quarkus</groupId>
            <artifactId>onecx-permissions</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-oidc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-oidc-filter</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.mockserver</groupId>
            <artifactId>quarkus-mockserver</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-test-keycloak-server</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.mockserver</groupId>
            <artifactId>quarkus-mockserver-test</artifactId>
${mockserverSwaggerParserExclusion}            <scope>test</scope>
        </dependency>
${legacyJunitDependencies}${legacySwaggerParser}    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <extensions>true</extensions>
            </plugin>
${backendDownloadPlugin}
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>frontend-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>src/main/openapi/${frontendApiFileName}</inputSpec>
                            <apiPackage>${internalApiPackage}</apiPackage>
                            <modelPackage>${internalModelPackage}</modelPackage>
                            <typeMappings>File=byte[],Object=Map</typeMappings>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <additionalProperties>onecx-permissions=true</additionalProperties>
                    <generatorName>jaxrs-spec</generatorName>
                    <apiNameSuffix>ApiService</apiNameSuffix>
                    <modelNameSuffix>DTO</modelNameSuffix>
                    <generateApiTests>false</generateApiTests>
                    <generateApiDocumentation>false</generateApiDocumentation>
                    <generateModelTests>false</generateModelTests>
                    <generateModelDocumentation>false</generateModelDocumentation>
                    <generateSupportingFiles>false</generateSupportingFiles>
                    <addCompileSourceRoot>true</addCompileSourceRoot>
                    <library>quarkus</library>
                    <configOptions>
                        <sourceFolder>/</sourceFolder>
                        <openApiNullable>false</openApiNullable>
                        <returnResponse>true</returnResponse>
                        <useTags>true</useTags>
                        <interfaceOnly>true</interfaceOnly>
                        <serializableModel>true</serializableModel>
                        <singleContentTypes>true</singleContentTypes>
                        <dateLibrary>java8</dateLibrary>
                        <useMicroProfileOpenAPIAnnotations>true</useMicroProfileOpenAPIAnnotations>
                        <useJakartaEe>true</useJakartaEe>
                        <useSwaggerAnnotations>false</useSwaggerAnnotations>
${openApiJavaOption}
                    </configOptions>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>







