# ${projectName}

Generated by `onecx-bff-generator`.

## Included assets

- frontend OpenAPI: `src/main/openapi/frontend/<original-file-name>`
- backend OpenAPI: `src/main/openapi/backend/<original-file-name>`
- generated controllers: `src/main/java/.../controller`
- generated models: `src/main/java/.../model/frontend` and `src/main/java/.../model/backend`
- generated mappers: `src/main/java/.../mapper`

## Project coordinates

- name: `${projectName}`
- group: `${groupId}`
- package: `${basePackage}`

## Parent setup

- onecx parent version: `${parentVersion}`
- dependency profile: `${dependencyProfile}`
- Java release: `${javaVersion}`

## Next steps

1. Review generated controller stubs and connect them to backend REST clients.
2. Review generated mapper classes and adjust non-trivial field mappings.
3. Build the project with Maven.


